# G23_k8s_nemesis.yaml
apiVersion: v1
kind: Service
metadata:
  name: electra-master-svc
spec:
  clusterIP: None
  selector:
    role: master
---
apiVersion: v1
kind: Pod
metadata:
  name: electra-master
  labels:
    role: master
spec:
  schedulerName: nemesis  # Triggers your Python Brain!
  restartPolicy: Never
  containers:
  - name: electra-container
    image: electra-sim:v1
    imagePullPolicy: IfNotPresent
    command: ["python", "G23_electra_train.py"]
    env:
    - name: MASTER_ADDR
      value: "electra-master-svc"
    - name: MASTER_PORT
      value: "29500"
    - name: WORLD_SIZE
      value: "2"
    - name: RANK
      value: "0"
---
apiVersion: v1
kind: Pod
metadata:
  name: electra-worker
  labels:
    role: worker
spec:
  schedulerName: nemesis  # Triggers your Python Brain!
  restartPolicy: Never
  containers:
  - name: electra-container
    image: electra-sim:v1
    imagePullPolicy: IfNotPresent
    command: ["python", "G23_electra_train.py"]
    env:
    - name: MASTER_ADDR
      value: "electra-master-svc"
    - name: MASTER_PORT
      value: "29500"
    - name: WORLD_SIZE
      value: "2"
    - name: RANK
      value: "1"
